### ISSUE TITLE
Git says it no longer authenticates with passwords and a personal access key is required.  Im trying to go through and figure this out but it is not meshing with terminal, the lesson, and git requirements for pushing

### ISSUE THREAD

**Issue by mvaneaton** [learn-co-curriculum/dsc-git-practice#3] opened 2022-06-24 20:21 UTC
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jilliankim** [comment] 2022-12-02 07:18
Closing this issue as the problem is not related to the repo itself.

**Closed as completed by jilliankim** 2022-12-02 07:18 UTC
